### ISSUE TITLE
refactoring of the bridge logic to work with authorities

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-parity-bridge-contracts#1]
I looked at the project swarmcity prepared: https://github.com/swarmcity/SCLabs-erc20-bridge/tree/master/contracts.

Seems that we can use great ideas for the bridge logic decomposition:
1. Since logic of working with authorities is the same for both bridge contracts introduce it in separate contract.
2. Do authorities as a map instead of an array. It will reduce gas consumption.

**Comment by akolotov** [comment]
And I will create an issue in the main project to address functionality of extendable list of authorities similar to https://github.com/paritytech/parity-bridge/issues/33.

**Comment by rstormsf** [comment]
@akolotov so I started learning this story and I couldn't understand what needs to be done.
